import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import clsx from "clsx";

import { Providers } from "@/app/providers";
import Header from "@/components/Header";

const satoshiFont = localFont({
  src: [
    { path: "../styles/fonts/Satoshi/Satoshi-Regular.otf", weight: "400" },
    { path: "../styles/fonts/Satoshi/Satoshi-Italic.otf", weight: "400" },
    { path: "../styles/fonts/Satoshi/Satoshi-Light.otf", weight: "300" },
    { path: "../styles/fonts/Satoshi/Satoshi-Medium.otf", weight: "500" },
    { path: "../styles/fonts/Satoshi/Satoshi-Bold.otf", weight: "700" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx("bg-background-page-body", satoshiFont.className)}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
